server:
  port: 5001



eureka:
  instance:
    hostname: eureka5001.com #eureka服务端实例名称
  client:
    register-with-eureka: false #false 代表不向注册中心注册自己
    fetch-registry: false #fasle 表示自己端就是注册中心， 我的职责就是维护服务实例  并不需要检索服务
    service-url:
      #单机defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka5002.com:5002/eureka/,http://eureka5003.com:5003/eureka/
